In [1]:
import _pickle as Pickle
import pandas as pd
import numpy as np
from sklearn.svm import LinearSVC

In [2]:
def unpickle(file):
    with open(file, 'rb') as fo:
        dict = Pickle.load(fo, encoding='bytes')
    return dict

In [3]:
dataPart1 = unpickle("cifar-10-batches-py/data_batch_1")
dataPart2 = unpickle("cifar-10-batches-py/data_batch_2")
dataPart3 = unpickle("cifar-10-batches-py/data_batch_3")
dataPart4 = unpickle("cifar-10-batches-py/data_batch_4")
dataPart5 = unpickle("cifar-10-batches-py/data_batch_5")
dataPartTest = unpickle("cifar-10-batches-py/test_batch")
dataPartMeta = unpickle("cifar-10-batches-py/batches.meta")

In [4]:
dataPart1.keys()

dict_keys([b'batch_label', b'labels', b'data', b'filenames'])

In [5]:
dataPart1[b'data']

array([[ 59,  43,  50, ..., 140,  84,  72],
       [154, 126, 105, ..., 139, 142, 144],
       [255, 253, 253, ...,  83,  83,  84],
       ...,
       [ 71,  60,  74, ...,  68,  69,  68],
       [250, 254, 211, ..., 215, 255, 254],
       [ 62,  61,  60, ..., 130, 130, 131]], dtype=uint8)

In [6]:
row = np.asarray([1, 2,3 ])
[1] + row

array([2, 3, 4])

In [7]:
def convertDataToDF(dataDict):
    dataFrame = pd.DataFrame(columns = ['Features / Colors'])
    columnLabels = np.asarray(dataDict[b'labels'])
    rowNumber = 0
    for row in dataPart1[b'data']:
        dataFrame.append(row)
    return dataframe

In [8]:
data = np.vstack([dataPart1[b'data'], dataPart2[b'data'], dataPart3[b'data'], dataPart4[b'data'], dataPart5[b'data']])

In [9]:
data.shape

(50000, 3072)

In [10]:
labels = np.hstack([dataPart1[b'labels'], dataPart2[b'labels'], dataPart3[b'labels'], dataPart4[b'labels'], dataPart5[b'labels']])






In [11]:
labels.shape

(50000,)

In [12]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [64]:
def makeModel():
    inputSize = 3072
    hiddenLayer1 = 500
    hiddenLayer2 = 200
    hiddenLayer3 = 128
    model = keras.Sequential(
    [
        layers.Dense(3072, activation="relu", name="layer1"),
        layers.Dense(hiddenLayer1, activation="relu", name="layer2"),
        layers.Dense(hiddenLayer2, activation="relu", name="layer3"),
        layers.Dense(hiddenLayer3, activation="relu", name="layer4"),
        layers.Dense(hiddenLayer3, activation="relu", name="layer5"),
        layers.Dense(10, activation="softmax", name="layer6"),
    ])
    return model

# keras.convolution neural network

In [65]:
model = makeModel()
loss = tf.keras.losses.CategoricalCrossentropy() # A parameter to do softmax implicitly from_logits
optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001 * 2)
model.compile(optimizer = optimizer, loss=loss, metrics = ['accuracy'])

In [43]:
def convertLabelsToArray(labels):
    newLabel = []
    for label in labels:
        newList= [0] *10
        newList[label-1] = 1
        newLabel.append(newList)
    return np.array(newLabel)

In [44]:
labelsArray = convertLabelsToArray(labels)
labelsArray.shape

(50000, 10)

In [66]:
model.fit(data, labelsArray)

1563/1563 [==============================] - 144s 92ms/step - loss: 14.6383 - accuracy: 0.2134


In [69]:
predictions = model.predict(dataPartTest[b'data'])

In [70]:
predictions
newPredictedLabels = convertPredictionsToLabels(predictions)
accuracy_score(newPredictedLabels, dataPartTest[b'labels'])

0.3069

In [30]:
predictions

array([[6.27403031e-04, 3.00849439e-03, 4.73574460e-01, ...,
        1.28936235e-05, 1.75179949e-03, 9.19392258e-02],
       [4.68452945e-02, 6.04702346e-03, 1.00187302e-01, ...,
        2.02606004e-02, 8.33066239e-04, 8.07837248e-01],
       [1.01903628e-04, 2.11095035e-08, 3.40662384e-03, ...,
        3.40295658e-02, 1.15597449e-01, 1.87013805e-01],
       ...,
       [7.49693208e-05, 3.45682984e-08, 1.57634751e-03, ...,
        8.24775780e-04, 8.34325179e-02, 9.13210988e-01],
       [6.07584625e-05, 8.53977599e-06, 2.81433435e-03, ...,
        1.34528995e-01, 1.07197827e-02, 7.58775055e-01],
       [5.96306381e-05, 2.19296795e-04, 4.19890182e-03, ...,
        5.39472909e-04, 5.12773730e-03, 9.15941224e-02]], dtype=float32)

In [38]:
def convertPredictionsToLabels(predictions):
    return [np.argmax(row) + 1 for row in predictions]

In [39]:
predictions
predictedLabels = convertPredictionsToLabels(predictions)
predictedLabels

[3,
 10,
 7,
 3,
 10,
 7,
 6,
 7,
 10,
 7,
 6,
 7,
 10,
 3,
 7,
 10,
 7,
 8,
 7,
 10,
 10,
 3,
 6,
 7,
 10,
 7,
 7,
 10,
 6,
 10,
 10,
 7,
 1,
 3,
 7,
 7,
 10,
 7,
 8,
 10,
 10,
 10,
 7,
 7,
 7,
 9,
 10,
 10,
 10,
 10,
 10,
 6,
 3,
 10,
 6,
 7,
 3,
 7,
 6,
 8,
 8,
 10,
 8,
 8,
 1,
 10,
 6,
 7,
 7,
 7,
 10,
 7,
 9,
 10,
 10,
 10,
 10,
 10,
 7,
 10,
 10,
 10,
 6,
 10,
 10,
 7,
 7,
 7,
 3,
 6,
 7,
 7,
 7,
 10,
 7,
 6,
 10,
 7,
 6,
 3,
 10,
 3,
 7,
 3,
 6,
 10,
 10,
 3,
 10,
 10,
 10,
 10,
 10,
 7,
 7,
 7,
 10,
 7,
 10,
 10,
 10,
 6,
 7,
 7,
 6,
 6,
 10,
 7,
 10,
 10,
 6,
 7,
 10,
 10,
 10,
 10,
 10,
 8,
 7,
 8,
 7,
 6,
 3,
 6,
 7,
 5,
 6,
 10,
 7,
 10,
 10,
 10,
 7,
 10,
 7,
 10,
 6,
 3,
 6,
 10,
 7,
 8,
 7,
 6,
 10,
 7,
 7,
 6,
 10,
 7,
 8,
 10,
 7,
 6,
 3,
 3,
 10,
 10,
 7,
 7,
 6,
 7,
 6,
 9,
 7,
 8,
 6,
 6,
 10,
 10,
 10,
 10,
 8,
 10,
 10,
 7,
 7,
 10,
 3,
 10,
 10,
 10,
 9,
 10,
 7,
 10,
 8,
 10,
 7,
 6,
 3,
 8,
 10,
 10,
 10,
 3,
 8,
 3,
 7,
 7,
 10,
 8,
 10,
 7,
 3,
 10,
 9,
 6,
 

In [40]:
from sklearn.metrics import accuracy_score
accuracy_score(predictedLabels, labels)

0.1839

In [ ]:
model1 = LinearSVC(random_state=0, max_iter=5000)
# reduce dimensions using PCA
#non-linear SVMS
model1.fit(data, labels)
# training_predictions = model.predict(mnist_train_sample)

In [22]:
from sklearn.metrics import accuracy_score
predictedLabels = model1.predict(dataPartTest[b'data'])
accuracy_score(predictedLabels, dataPartTest[b'labels'])

0.2391

In [ ]:
from keras.layers import Dense
model = Sequential()
model.add()

In [51]:
def makeDeeperModel():
    inputSize = 3072
    hiddenLayer1 = 300
    hiddenLayer2 = 100
    hiddenLayer3 = 64
    hiddenLayer4 = 64
    model = keras.Sequential(
    [
        layers.Dense(3072, activation="relu", name="layer1"),
        layers.Dense(hiddenLayer1, activation="relu", name="layer2"),
        layers.Dense(hiddenLayer2, activation="relu", name="layer3"),
        layers.Dense(hiddenLayer3, activation="relu", name="layer4"),
        layers.Dense(hiddenLayer4, activation="relu", name="layer5"),
        layers.Dense(10, activation="softmax", name="layer6")
    ])
    return model

In [52]:
newModel = makeDeeperModel()
loss = tf.keras.losses.CategoricalCrossentropy() # A parameter to do softmax implicitly from_logits
optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001 * 5)
newModel.compile(optimizer = optimizer, loss=loss, metrics = ['accuracy'] )

In [53]:
newModel.fit(data, labelsArray)

1563/1563 [==============================] - 137s 87ms/step - loss: 21.7046 - accuracy: 0.2002


In [55]:
smallerPredictions = newModel.predict(dataPartTest[b'data'])
newPredictedLabels = convertPredictionsToLabels(smallerPredictions)
accuracy_score(newPredictedLabels, dataPartTest[b'labels'])

0.2421

In [71]:
from sklearn.svm import NuSVC

In [ ]:
nonLinearSVM = NuSVC()
nonLinearSVM.fit(data, labels)

In [ ]:
predictedLabels = nonLinearSVM.predict(dataPartTest[b'data'])
accuracy_score(predictedLabels, dataPartTest[b'labels'])