In [2]:
import _pickle as Pickle
# import pandas as pd
import numpy as np
from sklearn.svm import LinearSVC

In [3]:
def unpickle(file):
    with open(file, 'rb') as fo:
        dict = Pickle.load(fo, encoding='bytes')
    return dict

In [4]:
dataPart1 = unpickle("cifar-10-batches-py/data_batch_1")
dataPart2 = unpickle("cifar-10-batches-py/data_batch_2")
dataPart3 = unpickle("cifar-10-batches-py/data_batch_3")
dataPart4 = unpickle("cifar-10-batches-py/data_batch_4")
dataPart5 = unpickle("cifar-10-batches-py/data_batch_5")
dataPartTest = unpickle("cifar-10-batches-py/test_batch")
dataPartMeta = unpickle("cifar-10-batches-py/batches.meta")

In [5]:
dataPart1.keys()

dict_keys([b'batch_label', b'labels', b'data', b'filenames'])

In [6]:
dataPart1[b'data']

array([[ 59,  43,  50, ..., 140,  84,  72],
       [154, 126, 105, ..., 139, 142, 144],
       [255, 253, 253, ...,  83,  83,  84],
       ...,
       [ 71,  60,  74, ...,  68,  69,  68],
       [250, 254, 211, ..., 215, 255, 254],
       [ 62,  61,  60, ..., 130, 130, 131]], dtype=uint8)

In [7]:
row = np.asarray([1, 2,3 ])
[1] + row

array([2, 3, 4])

In [8]:
def convertDataToDF(dataDict):
    dataFrame = pd.DataFrame(columns = ['Features / Colors'])
    columnLabels = np.asarray(dataDict[b'labels'])
    rowNumber = 0
    for row in dataPart1[b'data']:
        dataFrame.append(row)
    return dataframe

In [9]:
data = np.vstack([dataPart1[b'data'], dataPart2[b'data'], dataPart3[b'data'], dataPart4[b'data'], dataPart5[b'data']])

In [10]:
data.shape

(50000, 3072)

In [11]:
labels = np.hstack([dataPart1[b'labels'], dataPart2[b'labels'], dataPart3[b'labels'], dataPart4[b'labels'], dataPart5[b'labels']])






In [12]:
labels.shape

(50000,)

In [13]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [31]:
def makeModel(numberOfHiddedNodes = 3072):
    model = keras.Sequential(
    [
        layers.Dense(3072, activation="sigmoid", name="layer1"),
        layers.Dense(3072, activation="sigmoid", name="layer2"),
        layers.Dense(1000, activation="sigmoid", name="layer3"),
        layers.Dense(10, activation="sigmoid", name="layer4"),
    ])
    return model

In [46]:
model = makeModel()
losse = tf.keras.losses.CategoricalCrossentropy()
model.compile(optimizer = "adam", loss=losse, metrics = [tf.keras.metrics.Accuracy()])

In [47]:
def convertLabelsToArray(labels):
    newLabel = []
    for label in labels:
        newList = [0] *10
        newList[label-1] = 1
        newLabel.append(newList)
    return np.array(newLabel)

In [48]:
labelsArray = convertLabelsToArray(labels)
labelsArray.shape

(50000, 10)

In [49]:
model.fit(data, labelsArray)

1563/1563 [==============================] - 104s 66ms/step - loss: 2.4477 - accuracy: 0.0000e+00


In [55]:
predictions = model.predict(x=dataPartTest[b'data'])

In [56]:
predictions[0:4]
# sum(predictions[7])

array([[0.39108965, 0.37001425, 0.54124504, 0.6313185 , 0.24184957,
        0.51834965, 0.43425635, 0.43602273, 0.34751314, 0.51899254],
       [0.39109284, 0.37001044, 0.5412377 , 0.6313142 , 0.24184379,
        0.5183456 , 0.4342535 , 0.43603235, 0.34752616, 0.5189989 ],
       [0.39109284, 0.37001044, 0.5412377 , 0.6313142 , 0.24184379,
        0.5183456 , 0.4342535 , 0.43603235, 0.34752616, 0.5189989 ],
       [0.39109284, 0.37001044, 0.5412377 , 0.6313142 , 0.24184379,
        0.5183456 , 0.4342535 , 0.43603235, 0.34752616, 0.5189989 ]],
      dtype=float32)

In [20]:
model1 = LinearSVC(random_state=0, max_iter=5000)
model1.fit(data, labels)
# training_predictions = model.predict(mnist_train_sample)

/Users/vaibhavmohata/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


LinearSVC(max_iter=5000, random_state=0)

In [22]:
from sklearn.metrics import accuracy_score
predictedLabels = model1.predict(dataPartTest[b'data'])
accuracy_score(predictedLabels, dataPartTest[b'labels'])

0.2391

In [ ]:
from keras.layers import Dense
model = Sequential()
model.add()