In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

170500096/170498071 [==============================] - 303s 2us/step


In [10]:
x_train = x_train.reshape(50000, -1)
x_test = x_test.reshape(10000, -1)

In [14]:
temp1 = x_train
temp2 = x_test

In [15]:
# Standardizing the data to apply PCA later
from sklearn.preprocessing import StandardScaler
x_train = StandardScaler().fit_transform(x_train)
x_test = StandardScaler().fit_transform(x_test)

In [17]:
x_train.shape

(50000, 3072)

In [20]:
# Applying PCA
from sklearn.decomposition import PCA
pca = PCA(.90)
pca.fit(x_train)

PCA(n_components=0.9)

In [21]:
pca.n_components_

103

In [22]:
x_train = pca.transform(x_train)

In [23]:
x_test = pca.transform(x_test)

In [24]:
x_train.shape

(50000, 103)

In [25]:
x_test.shape

(10000, 103)

In [33]:
from sklearn.linear_model import LogisticRegression
import sklearn

In [27]:
logisticRegr = LogisticRegression()

In [28]:
logisticRegr.fit(x_train, y_train)

/Users/vaibhavmohata/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/vaibhavmohata/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [30]:
logisticRegr.predict(x_test)

array([3, 9, 8, ..., 3, 5, 7], dtype=uint8)

In [34]:
sklearn.metrics.accuracy_score(logisticRegr.predict(x_test), y_test)

0.4007

In [83]:
model = keras.Sequential(
    [
        layers.Dense(103, activation="relu", name="layer1"),
        layers.Dense(64, activation="relu", name="layer2"),
        layers.Dense(64, activation="relu", name="layer3"),
        layers.Dense(64, activation="relu", name="layer4"),
        layers.Dense(64, activation="relu", name="layer5"),
        layers.Dense(64, activation="relu", name="layer6"),
        layers.Dense(64, activation="relu", name="layer7"),
        layers.Dense(64, activation="relu", name="layer8"),
        layers.Dense(64, activation="relu", name="layer9"),
        layers.Dense(10, activation="softmax", name="layer10"),
    ])

In [84]:
loss = tf.keras.losses.CategoricalCrossentropy() # A parameter to do softmax implicitly from_logits
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer = optimizer, loss=loss, metrics = ['accuracy'])

In [66]:
def convertLabelsToArray(labels):
    newLabel = []
    for label in labels:
        newList= [0] *10
        newList[label[0]] = 1
        newLabel.append(newList)
    return np.array(newLabel)

In [72]:
newY_train = convertLabelsToArray(y_train)
newY_test = convertLabelsToArray(y_test)

In [85]:
model.fit(x_train, newY_train)

1563/1563 [==============================] - 3s 2ms/step - loss: 1.8918 - accuracy: 0.3009


m

In [100]:
model.predict(x_train)[3]

array([0.00796158, 0.01305661, 0.09274027, 0.07968314, 0.07660219,
       0.05625163, 0.64807934, 0.01719836, 0.00142014, 0.00700672],
      dtype=float32)

In [101]:
y_train[3]

array([4], dtype=uint8)

In [107]:
# from keras.datasets import cifar10
# from keras.utils import to_categorical
# from keras.models import Sequential
# from keras.layers import Conv2D
# from keras.layers import MaxPooling2D
# from keras.layers import Dense
# from keras.layers import Flatten
# from keras.optimizers import SGD
Flatten = keras.layers.Flatten
Dense = keras.layers.Dense
Conv2D = keras.layers.Conv2D
MaxPooling2D = keras.layers.MaxPooling2D
model = keras.models.Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
model.add(Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
model.add(MaxPooling2D((2, 2)))

In [108]:
model.add(Flatten())
model.add(Dense(128, activation='relu', kernel_initializer='he_uniform'))
model.add(Dense(10, activation='softmax'))

In [109]:
opt = keras.optimizers.SGD(lr=0.001, momentum=0.9)
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])

In [110]:
model.fit(x_train, y_train)

ValueError: in user code:

    /Users/vaibhavmohata/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
        return step_function(self, iterator)
    /Users/vaibhavmohata/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /Users/vaibhavmohata/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /Users/vaibhavmohata/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /Users/vaibhavmohata/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    /Users/vaibhavmohata/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:788 run_step  **
        outputs = model.train_step(data)
    /Users/vaibhavmohata/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:754 train_step
        y_pred = self(x, training=True)
    /Users/vaibhavmohata/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:998 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /Users/vaibhavmohata/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/input_spec.py:234 assert_input_compatibility
        raise ValueError('Input ' + str(input_index) + ' of layer ' +

    ValueError: Input 0 of layer sequential_6 is incompatible with the layer: : expected min_ndim=4, found ndim=2. Full shape received: (None, 103)
